### ISSUE TITLE
Shaders as importable functions?

### ISSUE THREAD

**Issue by quantenzitrone** [ikz87/picom-shaders#4]
When setting up the shaders in my rice, i realized that picom can't apply more than one shader per window, so i had to combine the border shader and the transparency shader to properly work together resulting in code redundancy in the shaders.
So i had this idea, that every shader could be transformed into a simple function that takes the pixel and/or coords and all the configuration options as function arguments.
This would make combining and reordering shaders easy.
Problem is, that glsl doesn't support any `#import` stuff so the functions would either need to be in the same file, or imported in some other funky way.
Having it in the same file doesn't remove code redundancy, but importing in other funky ways seems complicated as fuck:
https://stackoverflow.com/questions/25978295/import-function-from-different-shader
https://stackoverflow.com/questions/10754437/how-to-using-the-include-in-glsl-support-arb-shading-language-include

What do you think?

**Comment by ikz87** [comment]
Transforming shaders into functions is simply not possible for shaders that fetch multiple pixels in one `window_shader` call.

For example, let's say you want to first apply a `brigthness change` shader, and a `gaussian blur` afterwards. You change the brightness successfully and now are trying to apply the blur, which requieres the information of the pixel you're working with and it's neighbors. The thing is, you changed the brightness of the current pixel, but changed nothing about the actual texture of the window, so there's no way for you to fetch the neighbor pixels with the changes from the previous shader applied. Also there's no way to change the actual texture of the window in a way that works since the function calls happen in parallel. 

Imports wouldn't work anyway either, those would depend on some opengl code from picom itself as far as I know.

I have thought about this because all shaders in the `3D camera` section have a lot of redundant code, but sadly I don't think there's any good workaround :(. 

Though if you happen to somehow come up with a good solution, I'd happy to learn about it.
